USE strong_memory_db;

-- =========================
-- TABELAS
-- =========================

CREATE TABLE IF NOT EXISTS difficults(
	id TINYINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	difficulty VARCHAR(15) NOT NULL UNIQUE,
    translation VARCHAR(15) NOT NULL UNIQUE,
    max_quantity_words TINYINT NOT NULL,
    increase_display_time_seconds TINYINT NOT NULL,
    increase_typing_time_seconds TINYINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_roles(
    id TINYINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    role VARCHAR(25) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	role_id TINYINT NOT NULL,
	username VARCHAR(180) NOT NULL UNIQUE,
	email VARCHAR(120) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	FOREIGN KEY (role_id) REFERENCES user_roles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_score_records(
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT NOT NULL,
	difficulty_id TINYINT NOT NULL,
	score INT DEFAULT 0,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (difficulty_id) REFERENCES difficults(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS words (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	difficulty_id TINYINT NOT NULL,
	word VARCHAR(255) NOT NULL UNIQUE,
	INDEX(difficulty_id),
	FOREIGN KEY (difficulty_id) REFERENCES difficults(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS word_suggestions(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    suggested_word VARCHAR(255) NOT NULL,
    suggested_difficulty VARCHAR(15) NOT NULL,
	suggested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX(suggested_at),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
